services:
  juiceworld-dev:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    image: ${IMAGE_REPOSITORY:-juiceworld}/api:${IMAGE_TAG_EXTENDED:-latest}
    container_name: juiceworld-api
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${API_PORT:-6969}:${API_PORT:-6969}
    environment:
      - API_PORT=${API_PORT:-6969}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      - postgres
    volumes:
      - ${PWD}:/home/juiceworld

  postgres:
    image: postgres:alpine3.19
    container_name: juiceworld-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
